ApplicationId=agent-workbench
ApplicationTitle=Agent.Workbench
ApplicationLogo=awb1024
ApplicationContact=admin@xxx
ApplicationOwner=EnFlex.IT

# ============================================================
# Application Theme Overrides
# ============================================================
#
# All values are optional.
# Empty values use the Base Template defaults.
# ============================================================

ThemeLightPrimary=
ThemeLightBackground=
ThemeLightCard=
ThemeLightText=
ThemeLightBorder=
ThemeLightNotification=
ThemeLightHighlight=

ThemeDarkPrimary=
ThemeDarkBackground=
ThemeDarkCard=
ThemeDarkText=
ThemeDarkBorder=
ThemeDarkNotification=
ThemeDarkHighlight=

LegalImprintCompanyHomepage=
LegalImprintCompanyName=
LegalImprintEmail=admin@xxx