# ============================================================
# Base Template Metadata
# ============================================================
#
# This file contains metadata owned by the reusable Base
# Template.
#
# Concrete Applications must not modify these values as part
# of their Application configuration.
# ============================================================

TemplatePackageName=enflex.it-template
TemplateVersion=0.0.5