/* tslint:disable */
/* eslint-disable */
/**
 * Agent.Workbench REST - API
 * This is the REST-API for Agent.Workbench in an embbedded system mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@enflex.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * An Event that occured and can be logged
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * The time at which the event happened
     * @type {string}
     * @memberof Event
     */
    'time': string;
    /**
     * 
     * @type {EventLogTypes}
     * @memberof Event
     */
    'typeOfEvent'?: EventLogTypes;
    /**
     * the event that has happened
     * @type {string}
     * @memberof Event
     */
    'event': EventEventEnum;
}

export const EventEventEnum = {
    Running: 'Running',
    Starting: 'Starting',
    OpenProject: 'Open Project',
    StartingAgentSystem: 'Starting Agent System',
    UpdateSheduled: 'Update Sheduled',
    UpdateExecuted: 'Update Executed',
    UpdateFailure: 'Update Failure',
    UpdateInProgess: 'Update in Progess',
    RestartSheduled: 'Restart Sheduled',
    RestartExecuted: 'Restart Executed',
    RestartFailure: 'Restart Failure',
    RestartInProgess: 'Restart in Progess'
} as const;

export type EventEventEnum = typeof EventEventEnum[keyof typeof EventEventEnum];

/**
 * The different types of EventLogs
 * @export
 * @enum {string}
 */

export const EventLogTypes = {
    Awb: 'AWB',
    Project: 'Project',
    Setup: 'Setup',
    Agent: 'Agent'
} as const;

export type EventLogTypes = typeof EventLogTypes[keyof typeof EventLogTypes];


/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'dateTime': string;
    /**
     * 
     * @type {MessageType}
     * @memberof Message
     */
    'messageType': MessageType;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'message': string;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const MessageType = {
    Info: 'INFO',
    Warning: 'WARNING',
    Error: 'ERROR'
} as const;

export type MessageType = typeof MessageType[keyof typeof MessageType];


/**
 * Describes a single network connection.
 * @export
 * @interface NetworkConnection
 */
export interface NetworkConnection {
    /**
     * 
     * @type {string}
     * @memberof NetworkConnection
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof NetworkConnection
     */
    'displayName': string;
    /**
     * 
     * @type {string}
     * @memberof NetworkConnection
     */
    'macAddress': string;
    /**
     * 
     * @type {string}
     * @memberof NetworkConnection
     */
    'ip4Addresses': string;
    /**
     * 
     * @type {string}
     * @memberof NetworkConnection
     */
    'ip6Addresses': string;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnection
     */
    'trafficSendInMB': number;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnection
     */
    'trafficReceivedInMB': number;
}
/**
 * 
 * @export
 * @interface PasswordChange
 */
export interface PasswordChange {
    /**
     * 
     * @type {string}
     * @memberof PasswordChange
     */
    'password_old': string;
    /**
     * 
     * @type {string}
     * @memberof PasswordChange
     */
    'password_new': string;
}
/**
 * 
 * @export
 * @interface Properties
 */
export interface Properties {
    /**
     * 
     * @type {string}
     * @memberof Properties
     */
    'performative'?: string;
    /**
     * 
     * @type {Array<PropertyEntry>}
     * @memberof Properties
     */
    'propertyEntries': Array<PropertyEntry>;
}
/**
 * 
 * @export
 * @interface PropertyEntry
 */
export interface PropertyEntry {
    /**
     * 
     * @type {string}
     * @memberof PropertyEntry
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof PropertyEntry
     */
    'value': string;
    /**
     * 
     * @type {ValueType}
     * @memberof PropertyEntry
     */
    'valueType': ValueType;
    /**
     * 
     * @type {Array<string>}
     * @memberof PropertyEntry
     */
    'valueOptions'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyEntry
     */
    'valueOptionsOnly'?: boolean;
}


/**
 * 
 * @export
 * @interface SessionTimes
 */
export interface SessionTimes {
    /**
     * 
     * @type {number}
     * @memberof SessionTimes
     */
    'remainingTime': number;
    /**
     * 
     * @type {number}
     * @memberof SessionTimes
     */
    'expirationTime': number;
    /**
     * 
     * @type {number}
     * @memberof SessionTimes
     */
    'remainingTokenTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof SessionTimes
     */
    'tokenExpirationTime'?: number;
}
/**
 * 
 * @export
 * @interface SoftwareComponent
 */
export interface SoftwareComponent {
    /**
     * ID of the software component as for example symbolic bundle name or feature ID
     * @type {string}
     * @memberof SoftwareComponent
     */
    'ID'?: string;
    /**
     * human readable bundle or feature name
     * @type {string}
     * @memberof SoftwareComponent
     */
    'name'?: string;
    /**
     * 
     * @type {SoftwareComponentType}
     * @memberof SoftwareComponent
     */
    'componentType'?: SoftwareComponentType;
    /**
     * 
     * @type {Version}
     * @memberof SoftwareComponent
     */
    'version'?: Version;
}


/**
 * 
 * @export
 * @interface SoftwareComponentList
 */
export interface SoftwareComponentList {
    /**
     * 
     * @type {Array<SoftwareComponent>}
     * @memberof SoftwareComponentList
     */
    'SoftwareComponentList'?: Array<SoftwareComponent>;
}
/**
 * the type of software component that is either webApp, feature or bundle
 * @export
 * @enum {string}
 */

export const SoftwareComponentType = {
    Webapp: 'WEBAPP',
    Feature: 'FEATURE',
    Bundle: 'BUNDLE',
    BundleOfFeature: 'BUNDLE_OF_FEATURE'
} as const;

export type SoftwareComponentType = typeof SoftwareComponentType[keyof typeof SoftwareComponentType];


/**
 * The system information consisting of Hardware and OS information
 * @export
 * @interface SystemInformation
 */
export interface SystemInformation {
    /**
     * 
     * @type {string}
     * @memberof SystemInformation
     */
    'osDescription': string;
    /**
     * 
     * @type {string}
     * @memberof SystemInformation
     */
    'osManufacturer': string;
    /**
     * 
     * @type {string}
     * @memberof SystemInformation
     */
    'osFamilly': string;
    /**
     * 
     * @type {string}
     * @memberof SystemInformation
     */
    'osVersion': string;
    /**
     * 
     * @type {string}
     * @memberof SystemInformation
     */
    'processorName': string;
    /**
     * 
     * @type {number}
     * @memberof SystemInformation
     */
    'processorFrequenceInMhz': number;
    /**
     * 
     * @type {number}
     * @memberof SystemInformation
     */
    'processorNoPhysical': number;
    /**
     * 
     * @type {number}
     * @memberof SystemInformation
     */
    'processorNoLogical': number;
    /**
     * 
     * @type {number}
     * @memberof SystemInformation
     */
    'memoryTotalInGB': number;
    /**
     * 
     * @type {number}
     * @memberof SystemInformation
     */
    'swapMemoryTotalInGB': number;
    /**
     * 
     * @type {number}
     * @memberof SystemInformation
     */
    'heapMemoryMaxInGB': number;
    /**
     * 
     * @type {Array<NetworkConnection>}
     * @memberof SystemInformation
     */
    'networkConnections': Array<NetworkConnection>;
}
/**
 * The systems current load, includung CPU, memoryand HEAP  usage. Further, the number of Java threads are returned.
 * @export
 * @interface SystemLoad
 */
export interface SystemLoad {
    /**
     * The CPU usage in percent
     * @type {number}
     * @memberof SystemLoad
     */
    'cpuUsage': number;
    /**
     * The memory usage in percent
     * @type {number}
     * @memberof SystemLoad
     */
    'memUsage': number;
    /**
     * The Heap usage in percen
     * @type {number}
     * @memberof SystemLoad
     */
    'heapUsage': number;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const ValueType = {
    Integer: 'INTEGER',
    Boolean: 'BOOLEAN',
    String: 'STRING',
    Long: 'LONG',
    Double: 'DOUBLE'
} as const;

export type ValueType = typeof ValueType[keyof typeof ValueType];


/**
 * Object that holds Version Information.
 * @export
 * @interface Version
 */
export interface Version {
    /**
     * the major version number
     * @type {number}
     * @memberof Version
     */
    'major': number;
    /**
     * the minor version number
     * @type {number}
     * @memberof Version
     */
    'minor': number;
    /**
     * the micro version number
     * @type {number}
     * @memberof Version
     */
    'micro': number;
    /**
     * the version qualifier
     * @type {string}
     * @memberof Version
     */
    'qualifier': string;
}

/**
 * AdminsApi - axios parameter creator
 * @export
 */
export const AdminsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Download configuration file
         * @param {string} [xPerformative] Defines which configuration should be downloaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadAppSettingsFile: async (xPerformative?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/settings/download`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (xPerformative != null) {
                localVarHeaderParameter['X-Performative'] = String(xPerformative);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns Hardware and system  information. 
         * @summary Returns system information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        infoGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the current system load measured by Agent.Workbench that includes CPU-, memory- and Java Heap - load. Further, the number of threads and agents will be returnes 
         * @summary Returns the current System load
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loadGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/load`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Allows uploading configuration files via multipart/form-data. The X-Performative header defines the type of configuration file.
         * @summary Upload configuration file (binary)
         * @param {File} file The configuration file to upload
         * @param {string} [xPerformative] Defines which configuration should be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadAppSettingsFile: async (file: File, xPerformative?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadAppSettingsFile', 'file', file)
            const localVarPath = `/app/settings/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            if (xPerformative != null) {
                localVarHeaderParameter['X-Performative'] = String(xPerformative);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminsApi - functional programming interface
 * @export
 */
export const AdminsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Download configuration file
         * @param {string} [xPerformative] Defines which configuration should be downloaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadAppSettingsFile(xPerformative?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadAppSettingsFile(xPerformative, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminsApi.downloadAppSettingsFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns Hardware and system  information. 
         * @summary Returns system information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async infoGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemInformation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.infoGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminsApi.infoGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the current system load measured by Agent.Workbench that includes CPU-, memory- and Java Heap - load. Further, the number of threads and agents will be returnes 
         * @summary Returns the current System load
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loadGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemLoad>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loadGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminsApi.loadGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Allows uploading configuration files via multipart/form-data. The X-Performative header defines the type of configuration file.
         * @summary Upload configuration file (binary)
         * @param {File} file The configuration file to upload
         * @param {string} [xPerformative] Defines which configuration should be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadAppSettingsFile(file: File, xPerformative?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Message>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadAppSettingsFile(file, xPerformative, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminsApi.uploadAppSettingsFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminsApi - factory interface
 * @export
 */
export const AdminsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminsApiFp(configuration)
    return {
        /**
         * 
         * @summary Download configuration file
         * @param {string} [xPerformative] Defines which configuration should be downloaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadAppSettingsFile(xPerformative?: string, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.downloadAppSettingsFile(xPerformative, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns Hardware and system  information. 
         * @summary Returns system information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        infoGet(options?: RawAxiosRequestConfig): AxiosPromise<SystemInformation> {
            return localVarFp.infoGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the current system load measured by Agent.Workbench that includes CPU-, memory- and Java Heap - load. Further, the number of threads and agents will be returnes 
         * @summary Returns the current System load
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loadGet(options?: RawAxiosRequestConfig): AxiosPromise<SystemLoad> {
            return localVarFp.loadGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Allows uploading configuration files via multipart/form-data. The X-Performative header defines the type of configuration file.
         * @summary Upload configuration file (binary)
         * @param {File} file The configuration file to upload
         * @param {string} [xPerformative] Defines which configuration should be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadAppSettingsFile(file: File, xPerformative?: string, options?: RawAxiosRequestConfig): AxiosPromise<Message> {
            return localVarFp.uploadAppSettingsFile(file, xPerformative, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminsApi - object-oriented interface
 * @export
 * @class AdminsApi
 * @extends {BaseAPI}
 */
export class AdminsApi extends BaseAPI {
    /**
     * 
     * @summary Download configuration file
     * @param {string} [xPerformative] Defines which configuration should be downloaded
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminsApi
     */
    public downloadAppSettingsFile(xPerformative?: string, options?: RawAxiosRequestConfig) {
        return AdminsApiFp(this.configuration).downloadAppSettingsFile(xPerformative, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns Hardware and system  information. 
     * @summary Returns system information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminsApi
     */
    public infoGet(options?: RawAxiosRequestConfig) {
        return AdminsApiFp(this.configuration).infoGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the current system load measured by Agent.Workbench that includes CPU-, memory- and Java Heap - load. Further, the number of threads and agents will be returnes 
     * @summary Returns the current System load
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminsApi
     */
    public loadGet(options?: RawAxiosRequestConfig) {
        return AdminsApiFp(this.configuration).loadGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Allows uploading configuration files via multipart/form-data. The X-Performative header defines the type of configuration file.
     * @summary Upload configuration file (binary)
     * @param {File} file The configuration file to upload
     * @param {string} [xPerformative] Defines which configuration should be updated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminsApi
     */
    public uploadAppSettingsFile(file: File, xPerformative?: string, options?: RawAxiosRequestConfig) {
        return AdminsApiFp(this.configuration).uploadAppSettingsFile(file, xPerformative, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * InfoApi - axios parameter creator
 * @export
 */
export const InfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aliveGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/alive`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get logs of specific type
         * @param {EventLogTypes} type The type which is retrieved by awb
         * @param {number} [amount] the maximum number of logs to retrieve. If no number is specified the default is 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventLogGet: async (type: EventLogTypes, amount?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('eventLogGet', 'type', type)
            const localVarPath = `/eventLog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (amount !== undefined) {
                localVarQueryParameter['amount'] = amount;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns required base configuration settings for the curren web application
         * @summary Returns required base configuration settings for the curren web application
         * @param {string} [xPerformative] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppSettings: async (xPerformative?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/settings/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (xPerformative != null) {
                localVarHeaderParameter['X-Performative'] = String(xPerformative);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enables to update or set the required base configuration settings for the curren web application
         * @summary Enables to update or set the required base configuration settings for the curren web application
         * @param {Properties} [properties] The new settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setAppSettings: async (properties?: Properties, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/settings/set`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(properties, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return the current version number of Agent.Workbench
         * @param {SoftwareComponentType} [type] 
         * @param {string} [filter] 
         * @param {boolean} [isShowSource] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        versionGet: async (type?: SoftwareComponentType, filter?: string, isShowSource?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/version`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (isShowSource !== undefined) {
                localVarQueryParameter['isShowSource'] = isShowSource;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InfoApi - functional programming interface
 * @export
 */
export const InfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aliveGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aliveGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InfoApi.aliveGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary get logs of specific type
         * @param {EventLogTypes} type The type which is retrieved by awb
         * @param {number} [amount] the maximum number of logs to retrieve. If no number is specified the default is 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eventLogGet(type: EventLogTypes, amount?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Event>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eventLogGet(type, amount, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InfoApi.eventLogGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns required base configuration settings for the curren web application
         * @summary Returns required base configuration settings for the curren web application
         * @param {string} [xPerformative] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAppSettings(xPerformative?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Properties>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAppSettings(xPerformative, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InfoApi.getAppSettings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Enables to update or set the required base configuration settings for the curren web application
         * @summary Enables to update or set the required base configuration settings for the curren web application
         * @param {Properties} [properties] The new settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setAppSettings(properties?: Properties, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Message>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setAppSettings(properties, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InfoApi.setAppSettings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Return the current version number of Agent.Workbench
         * @param {SoftwareComponentType} [type] 
         * @param {string} [filter] 
         * @param {boolean} [isShowSource] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async versionGet(type?: SoftwareComponentType, filter?: string, isShowSource?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SoftwareComponentList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.versionGet(type, filter, isShowSource, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InfoApi.versionGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InfoApi - factory interface
 * @export
 */
export const InfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InfoApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aliveGet(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.aliveGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get logs of specific type
         * @param {EventLogTypes} type The type which is retrieved by awb
         * @param {number} [amount] the maximum number of logs to retrieve. If no number is specified the default is 10
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventLogGet(type: EventLogTypes, amount?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<Event>> {
            return localVarFp.eventLogGet(type, amount, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns required base configuration settings for the curren web application
         * @summary Returns required base configuration settings for the curren web application
         * @param {string} [xPerformative] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppSettings(xPerformative?: string, options?: RawAxiosRequestConfig): AxiosPromise<Properties> {
            return localVarFp.getAppSettings(xPerformative, options).then((request) => request(axios, basePath));
        },
        /**
         * Enables to update or set the required base configuration settings for the curren web application
         * @summary Enables to update or set the required base configuration settings for the curren web application
         * @param {Properties} [properties] The new settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setAppSettings(properties?: Properties, options?: RawAxiosRequestConfig): AxiosPromise<Message> {
            return localVarFp.setAppSettings(properties, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return the current version number of Agent.Workbench
         * @param {SoftwareComponentType} [type] 
         * @param {string} [filter] 
         * @param {boolean} [isShowSource] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        versionGet(type?: SoftwareComponentType, filter?: string, isShowSource?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<SoftwareComponentList> {
            return localVarFp.versionGet(type, filter, isShowSource, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InfoApi - object-oriented interface
 * @export
 * @class InfoApi
 * @extends {BaseAPI}
 */
export class InfoApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoApi
     */
    public aliveGet(options?: RawAxiosRequestConfig) {
        return InfoApiFp(this.configuration).aliveGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get logs of specific type
     * @param {EventLogTypes} type The type which is retrieved by awb
     * @param {number} [amount] the maximum number of logs to retrieve. If no number is specified the default is 10
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoApi
     */
    public eventLogGet(type: EventLogTypes, amount?: number, options?: RawAxiosRequestConfig) {
        return InfoApiFp(this.configuration).eventLogGet(type, amount, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns required base configuration settings for the curren web application
     * @summary Returns required base configuration settings for the curren web application
     * @param {string} [xPerformative] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoApi
     */
    public getAppSettings(xPerformative?: string, options?: RawAxiosRequestConfig) {
        return InfoApiFp(this.configuration).getAppSettings(xPerformative, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Enables to update or set the required base configuration settings for the curren web application
     * @summary Enables to update or set the required base configuration settings for the curren web application
     * @param {Properties} [properties] The new settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoApi
     */
    public setAppSettings(properties?: Properties, options?: RawAxiosRequestConfig) {
        return InfoApiFp(this.configuration).setAppSettings(properties, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return the current version number of Agent.Workbench
     * @param {SoftwareComponentType} [type] 
     * @param {string} [filter] 
     * @param {boolean} [isShowSource] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoApi
     */
    public versionGet(type?: SoftwareComponentType, filter?: string, isShowSource?: boolean, options?: RawAxiosRequestConfig) {
        return InfoApiFp(this.configuration).versionGet(type, filter, isShowSource, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Changes the user password
         * @param {PasswordChange} [passwordChange] The credentials to login.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (passwordChange?: PasswordChange, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/pswd-change`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passwordChange, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the remaining session time as well as the expiration time
         * @summary Extends and returns the remaining and the expiration time of the current user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extendSessionTime: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/sessionTime/extend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the remaining session time as well as the expiration time
         * @summary Enables to read the remaining and the expiration time of the current user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionTime: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/sessionTime`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Does NOT use Bearer Auth like whole other application. Only Endpoint that uses Basic Authentication. Expects previously configured Credentials and returns appropriate Bearer Token
         * @summary Logs user into the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Effectively logs-out the user from the System 
         * @summary Logs out the user from the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Changes the user password
         * @param {PasswordChange} [passwordChange] The credentials to login.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(passwordChange?: PasswordChange, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(passwordChange, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.changePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the remaining session time as well as the expiration time
         * @summary Extends and returns the remaining and the expiration time of the current user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async extendSessionTime(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SessionTimes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.extendSessionTime(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.extendSessionTime']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the remaining session time as well as the expiration time
         * @summary Enables to read the remaining and the expiration time of the current user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSessionTime(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SessionTimes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSessionTime(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getSessionTime']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Does NOT use Bearer Auth like whole other application. Only Endpoint that uses Basic Authentication. Expects previously configured Credentials and returns appropriate Bearer Token
         * @summary Logs user into the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.loginUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Effectively logs-out the user from the System 
         * @summary Logs out the user from the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Changes the user password
         * @param {PasswordChange} [passwordChange] The credentials to login.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(passwordChange?: PasswordChange, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.changePassword(passwordChange, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the remaining session time as well as the expiration time
         * @summary Extends and returns the remaining and the expiration time of the current user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extendSessionTime(options?: RawAxiosRequestConfig): AxiosPromise<SessionTimes> {
            return localVarFp.extendSessionTime(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the remaining session time as well as the expiration time
         * @summary Enables to read the remaining and the expiration time of the current user session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionTime(options?: RawAxiosRequestConfig): AxiosPromise<SessionTimes> {
            return localVarFp.getSessionTime(options).then((request) => request(axios, basePath));
        },
        /**
         * Does NOT use Bearer Auth like whole other application. Only Endpoint that uses Basic Authentication. Expects previously configured Credentials and returns appropriate Bearer Token
         * @summary Logs user into the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.loginUser(options).then((request) => request(axios, basePath));
        },
        /**
         * Effectively logs-out the user from the System 
         * @summary Logs out the user from the system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Changes the user password
     * @param {PasswordChange} [passwordChange] The credentials to login.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public changePassword(passwordChange?: PasswordChange, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).changePassword(passwordChange, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the remaining session time as well as the expiration time
     * @summary Extends and returns the remaining and the expiration time of the current user session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public extendSessionTime(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).extendSessionTime(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the remaining session time as well as the expiration time
     * @summary Enables to read the remaining and the expiration time of the current user session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getSessionTime(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getSessionTime(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Does NOT use Bearer Auth like whole other application. Only Endpoint that uses Basic Authentication. Expects previously configured Credentials and returns appropriate Bearer Token
     * @summary Logs user into the system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public loginUser(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).loginUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Effectively logs-out the user from the System 
     * @summary Logs out the user from the system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public logout(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }
}



