name: Export Put Release

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Update npm
        run: npm install -g npm@10

      - name: Show versions after npm update
        run: |
          node -v
          npm -v

      - name: Install Repository
        run: npm ci

      - name: Set version
        id: version-selector
        run: echo "version=$(grep version package.json | cut -d '"' -f 4 | head -n1)" >> "$GITHUB_OUTPUT"

      - name: Set time
        id: time-selector
        run: echo "time=$(date +%Y%m%d-%H%M)" >> "$GITHUB_OUTPUT"

      - name: Export
        run: npx expo export -p web

      - name: Package
        env:
          name: ${{ secrets.PROJECT_NAME }}_${{ steps.version-selector.outputs.version }}_${{ steps.time-selector.outputs.time }}
        run: cd dist && zip -r ../$name.zip .

      - name: Put
        env:
          url: ${{ secrets.FTP_UPLOAD_URL }}
          user: ${{ secrets.FTP_USER }}
          pwd: ${{ secrets.FTP_PSWD }}
          name: ${{ secrets.PROJECT_NAME }}_${{ steps.version-selector.outputs.version }}_${{ steps.time-selector.outputs.time }}
          path: ${{ secrets.PROJECT_PATH }}
        run: printf "open $url\nuser $user $pwd\ncd $path\nput $name.zip\nexit" | ftp -n

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ secrets.PROJECT_NAME }}_${{ steps.version-selector.outputs.version }}_${{ steps.time-selector.outputs.time }}.zip
          tag_name: v${{ steps.version-selector.outputs.version }}